apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-servicemonitor #nome ?
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 30s





      #ServiceMonitor para o Prometheus coletar métricas do NGINX
      #O Prometheus precisa saber onde buscar as métricas do NGINX. O kube-prometheus-stack usa o recurso ServiceMonitor para isso.

